#include "host/RemoteReachability.hpp"
#include <gtest/gtest.h>
#include <array>
#include <chrono>
#include <thread>
#if defined(__linux__)
#include <arpa/inet.h>
#include <sys/socket.h>
#include <unistd.h>
#endif
namespace {
#if defined(__linux__)
using namespace std::chrono_literals;
struct Resolver final:softadastra::LocalGatewayTargetResolver { softadastra::LocalGatewayTarget target{}; softadastra::LocalGatewayTarget resolve(std::string_view name)const override{return name=="app"?target:softadastra::LocalGatewayTarget{};} };
int listener(std::uint16_t &port){int fd=::socket(AF_INET,SOCK_STREAM,0);sockaddr_in a{};a.sin_family=AF_INET;a.sin_addr.s_addr=htonl(INADDR_LOOPBACK);if(fd<0||::bind(fd,reinterpret_cast<sockaddr*>(&a),sizeof(a))||::listen(fd,4)){if(fd>=0)::close(fd);return -1;}socklen_t n=sizeof(a);::getsockname(fd,reinterpret_cast<sockaddr*>(&a),&n);port=ntohs(a.sin_port);return fd;}
bool all(int fd,const std::string &v){for(std::size_t n=0;n<v.size();){auto r=::send(fd,v.data()+n,v.size()-n,0);if(r<=0)return false;n+=r;}return true;} bool receive(int fd,char *p,std::size_t n){for(std::size_t at=0;at<n;){auto r=::recv(fd,p+at,n-at,0);if(r<=0)return false;at+=r;}return true;}
void put16(std::string &v,std::uint16_t n){v.push_back(static_cast<char>(n>>8));v.push_back(static_cast<char>(n));}void put32(std::string &v,std::uint32_t n){v.push_back(static_cast<char>(n>>24));v.push_back(static_cast<char>(n>>16));v.push_back(static_cast<char>(n>>8));v.push_back(static_cast<char>(n));}
bool frame(int fd,const std::string &body){std::string h;put32(h,body.size());return all(fd,h)&&all(fd,body);}std::string get_frame(int fd){std::array<char,4> h{};if(!receive(fd,h.data(),4))return {};auto n=(static_cast<unsigned char>(h[0])<<24)|(static_cast<unsigned char>(h[1])<<16)|(static_cast<unsigned char>(h[2])<<8)|static_cast<unsigned char>(h[3]);std::string r(n,'\0');return receive(fd,r.data(),n)?r:std::string{};}
std::string request(std::string method,std::string path,std::string body={}){std::string f(1,1);put16(f,3);f+="app";put16(f,method.size());f+=method;put32(f,path.size());f+=path;put16(f,1);put16(f,6);f+="X-Test";put16(f,2);f+="ok";put32(f,body.size());f+=body;return f;}
bool wait_state(const softadastra::RemoteReachability &r,softadastra::RemoteReachabilityState s){for(int i=0;i<100;++i){if(r.state()==s)return true;std::this_thread::sleep_for(10ms);}return false;}
TEST(RemoteReachabilityTest, UsesOutboundRelayAndSharedHttpProxy) {std::uint16_t backend_port{},relay_port{};int backend=listener(backend_port),relay=listener(relay_port);ASSERT_GE(backend,0);ASSERT_GE(relay,0);std::string seen;std::thread web([&]{int c=::accept(backend,nullptr,nullptr);std::array<char,4096>b{};ssize_t n;while((n=::recv(c,b.data(),b.size(),0))>0)seen.append(b.data(),n);all(c,"HTTP/1.1 200 OK\r\nContent-Length: 2\r\n\r\nOK");::close(c);::close(backend);});Resolver resolver;resolver.target={softadastra::LocalGatewayLookup::Http,backend_port};softadastra::RemoteReachability remote(resolver);remote.configure({"127.0.0.1",relay_port});int host=::accept(relay,nullptr,nullptr);ASSERT_GE(host,0);ASSERT_TRUE(wait_state(remote,softadastra::RemoteReachabilityState::Ready));ASSERT_TRUE(frame(host,request("POST","/echo?q=1","body")));const auto answer=get_frame(host);EXPECT_TRUE(answer.starts_with(std::string(1,2)+"HTTP/1.1 200"));EXPECT_NE(seen.find("POST /echo?q=1 HTTP/1.1"),std::string::npos);EXPECT_NE(seen.find("X-Test: ok"),std::string::npos);EXPECT_NE(seen.find("\r\n\r\nbody"),std::string::npos);::close(host);EXPECT_TRUE(wait_state(remote,softadastra::RemoteReachabilityState::Degraded));int again=::accept(relay,nullptr,nullptr);ASSERT_GE(again,0);EXPECT_TRUE(wait_state(remote,softadastra::RemoteReachabilityState::Ready));remote.disable();EXPECT_EQ(remote.state(),softadastra::RemoteReachabilityState::Disabled);::close(again);::close(relay);web.join();}
TEST(RemoteReachabilityTest, ReturnsResolvedErrorsAndRejectsMalformedAndOversizedFrames) {std::uint16_t relay_port{};int relay=listener(relay_port);ASSERT_GE(relay,0);Resolver resolver;softadastra::RemoteReachability remote(resolver);remote.configure({"127.0.0.1",relay_port});int host=::accept(relay,nullptr,nullptr);ASSERT_GE(host,0);ASSERT_TRUE(frame(host,request("GET","/missing")));EXPECT_TRUE(get_frame(host).find(" 404 Not Found")!=std::string::npos);resolver.target={softadastra::LocalGatewayLookup::Unavailable,0};ASSERT_TRUE(frame(host,request("GET","/stopped")));EXPECT_TRUE(get_frame(host).find(" 503 Service Unavailable")!=std::string::npos);ASSERT_TRUE(frame(host,std::string(1,1)));::close(host);EXPECT_TRUE(wait_state(remote,softadastra::RemoteReachabilityState::Degraded));int malformed=::accept(relay,nullptr,nullptr);ASSERT_GE(malformed,0);std::string oversize;put32(oversize,1024*1024+1);ASSERT_TRUE(all(malformed,oversize));::close(malformed);EXPECT_TRUE(wait_state(remote,softadastra::RemoteReachabilityState::Degraded));remote.disable();::close(relay);}
#endif
}
