#include "host/LocalDns.hpp"
#include "software/LocalName.hpp"
#include <array>
#include <thread>
#if defined(__linux__)
#include <arpa/inet.h>
#include <sys/socket.h>
#include <unistd.h>
#endif
namespace { constexpr std::string_view zone="softadastra.home.arpa"; constexpr std::size_t maximum_packet=512;
std::uint16_t read16(const std::string &v,std::size_t p){return (static_cast<unsigned char>(v[p])<<8)|static_cast<unsigned char>(v[p+1]);}
void write16(std::string &v,std::uint16_t n){v.push_back(static_cast<char>(n>>8));v.push_back(static_cast<char>(n));}
bool qname(const std::string &q,std::size_t &p,std::string &name){while(p<q.size()){const auto n=static_cast<unsigned char>(q[p++]);if(n==0)return !name.empty();if(n>63||p+n>q.size())return false;if(!name.empty())name+='.';name.append(q,p,n);p+=n;}return false;}
std::string response(const std::string &q,const std::string &address){if(q.size()<12)return {};const auto id=read16(q,0);const auto flags=read16(q,2);std::uint16_t code=0,answers=0;std::size_t p=12;std::string name;bool valid=read16(q,4)==1&&read16(q,6)==0&&read16(q,8)==0&&read16(q,10)==0&&qname(q,p,name)&&p+4==q.size();std::uint16_t type=0,klass=0;if(valid){type=read16(q,p);klass=read16(q,p+2);const auto suffix="."+std::string(zone);const bool in_zone=name.ends_with(suffix);const auto label=in_zone?name.substr(0,name.size()-suffix.size()):"";valid=in_zone&&softadastra::LocalName::from_software_name(label).has_value();if(!valid)code=3;else if(type==1&&klass==1)answers=1;}else code=1;std::string r;write16(r,id);write16(r,static_cast<std::uint16_t>(0x8000|0x0400|(flags&0x0100)|code));write16(r,valid?1:0);write16(r,answers);write16(r,0);write16(r,0);if(valid){r.append(q,12,p+4-12);if(answers){write16(r,0xc00c);write16(r,1);write16(r,1);r.append("\0\0\0\36",4);write16(r,4);in_addr a{};if(::inet_pton(AF_INET,address.c_str(),&a)!=1)return {};r.append(reinterpret_cast<const char*>(&a.s_addr),4);}}return r;}}
namespace softadastra {class LocalDns::Thread:public std::thread{public:using std::thread::thread;};LocalDns::~LocalDns(){stop();}bool LocalDns::start(std::string address,std::uint16_t port){if(descriptor_>=0)return false;int fd=::socket(AF_INET,SOCK_DGRAM,0);sockaddr_in a{};a.sin_family=AF_INET;a.sin_port=htons(port);if(fd<0||::inet_pton(AF_INET,address.c_str(),&a.sin_addr)!=1||::bind(fd,reinterpret_cast<sockaddr*>(&a),sizeof(a))){if(fd>=0)::close(fd);status_.state=LocalDnsState::Failed;return false;}socklen_t n=sizeof(a);if(::getsockname(fd,reinterpret_cast<sockaddr*>(&a),&n)){::close(fd);status_.state=LocalDnsState::Failed;return false;}descriptor_=fd;stopping_=false;status_={LocalDnsState::Running,std::move(address),ntohs(a.sin_port)};thread_=new Thread([this]{run();});return true;}void LocalDns::stop()noexcept{stopping_=true;if(descriptor_>=0){::shutdown(descriptor_,SHUT_RDWR);::close(descriptor_);descriptor_=-1;}if(thread_){thread_->join();delete thread_;thread_=nullptr;}status_={};}LocalDnsStatus LocalDns::status()const{return status_;}void LocalDns::run()noexcept{std::array<char,maximum_packet>b{};while(!stopping_){sockaddr_in peer{};socklen_t n=sizeof(peer);auto got=::recvfrom(descriptor_,b.data(),b.size(),0,reinterpret_cast<sockaddr*>(&peer),&n);if(got<=0)continue;const auto r=response(std::string(b.data(),static_cast<std::size_t>(got)),status_.address);if(!r.empty())static_cast<void>(::sendto(descriptor_,r.data(),r.size(),0,reinterpret_cast<sockaddr*>(&peer),n));}}}
