#include "host/LocalGateway.hpp"
#include "host/HostService.hpp"
#include <array>
#include <algorithm>
#include <cctype>
#include <set>
#include <sstream>
#include <thread>
#if defined(__linux__)
#include <arpa/inet.h>
#include <sys/socket.h>
#include <unistd.h>
#endif
namespace { constexpr std::size_t max_headers=32768,max_body=1048576,max_line=8192;
std::string lower(std::string v){for(char &c:v)c=static_cast<char>(std::tolower(static_cast<unsigned char>(c)));return v;}
std::string header_name(std::string value){bool upper=true;for(char &c:value){if(upper)c=static_cast<char>(std::toupper(static_cast<unsigned char>(c)));else c=static_cast<char>(std::tolower(static_cast<unsigned char>(c)));upper=c=='-';}return value;}
bool send_all(int fd,const std::string &v){for(std::size_t n=0;n<v.size();){const auto r=::send(fd,v.data()+n,v.size()-n,0);if(r<=0)return false;n+=static_cast<std::size_t>(r);}return true;}
void reply(int fd,int c,const char *r){static_cast<void>(send_all(fd,"HTTP/1.1 "+std::to_string(c)+" "+r+"\r\nContent-Length: 0\r\nConnection: close\r\n\r\n"));}
struct Msg{std::string first,body;std::vector<std::pair<std::string,std::string>> headers;};
bool parse(std::string &raw,Msg &m,bool request){const auto end=raw.find("\r\n\r\n"),first=raw.find("\r\n");if(end==std::string::npos||first==std::string::npos||first>max_line)return false;m.first=raw.substr(0,first);std::size_t p=first+2;std::optional<std::size_t> length;while(p<end){const auto e=raw.find("\r\n",p),c=raw.find(':',p);if(e==std::string::npos||c==std::string::npos||c>=e)return false;auto k=lower(raw.substr(p,c-p));auto v=raw.substr(c+1,e-c-1);while(!v.empty()&&(v.front()==' '||v.front()=='\t'))v.erase(0,1);if(k=="transfer-encoding")return false;if(k=="content-length"){if(length||v.empty()||!std::all_of(v.begin(),v.end(),[](unsigned char x){return std::isdigit(x);}))return false;try{length=std::stoull(v);}catch(...){return false;}if(*length>max_body)return false;}m.headers.emplace_back(std::move(k),std::move(v));p=e+2;}if(request){std::istringstream s(m.first);std::string a,b,c,d;if(!(s>>a>>b>>c)||s>>d||b.empty()||b.front()!='/'||c!="HTTP/1.1")return false;}const auto n=length.value_or(0);if(raw.size()<end+4+n)return false;m.body.assign(raw.data()+end+4,n);return true;}
bool read_request(int fd,Msg &m){std::string raw;std::array<char,4096>b{};while(raw.find("\r\n\r\n")==std::string::npos){auto r=::recv(fd,b.data(),b.size(),0);if(r<=0||raw.size()+static_cast<std::size_t>(r)>max_headers)return false;raw.append(b.data(),static_cast<std::size_t>(r));}const auto end=raw.find("\r\n\r\n");auto lower_head=lower(raw.substr(0,end));std::size_t n=0;auto at=lower_head.find("\r\ncontent-length:");if(at!=std::string::npos){auto e=raw.find("\r\n",at+17);try{n=std::stoull(raw.substr(at+17,e-at-17));}catch(...){return false;}if(n>max_body)return false;}while(raw.size()<end+4+n){auto r=::recv(fd,b.data(),b.size(),0);if(r<=0||raw.size()+static_cast<std::size_t>(r)>max_headers+max_body)return false;raw.append(b.data(),static_cast<std::size_t>(r));}return parse(raw,m,true);}
std::set<std::string> hops(const Msg&m){std::set<std::string>x{"connection","proxy-connection","keep-alive","te","trailer","transfer-encoding","upgrade"};for(const auto&[k,v]:m.headers)if(k=="connection"){std::istringstream s(v);std::string t;while(std::getline(s,t,',')){while(!t.empty()&&t.front()==' ')t.erase(0,1);x.insert(lower(t));}}return x;}
std::string hostname(const Msg&m){std::string x;for(const auto&[k,v]:m.headers)if(k=="host"){if(!x.empty()&&x!=v)return {};x=v;}if(x.empty()||x.find('/')!=std::string::npos||x.find('@')!=std::string::npos)return {};auto p=x.rfind(':');if(p!=std::string::npos){if(x.find(':')!=p||p==0||p+1==x.size()||!std::all_of(x.begin()+p+1,x.end(),[](unsigned char c){return std::isdigit(c);}))return {};x.resize(p);}return lower(x);}
std::string wire(const Msg&m){auto blocked=hops(m);std::string r=m.first+"\r\n";for(const auto&[k,v]:m.headers)if(!blocked.contains(k))r+=header_name(k)+": "+v+"\r\n";return r+"Connection: close\r\n\r\n"+m.body;}
bool read_response(int fd,Msg&m){std::string raw;std::array<char,8192>b{};for(;;){auto r=::recv(fd,b.data(),b.size(),0);if(r==0)break;if(r<0||raw.size()+static_cast<std::size_t>(r)>max_headers+max_body)return false;raw.append(b.data(),static_cast<std::size_t>(r));}return parse(raw,m,false);}}
namespace softadastra {class LocalGateway::Thread:public std::thread{public:using std::thread::thread;};LocalGateway::LocalGateway(HostService&s)noexcept:host_service_(s){}LocalGateway::~LocalGateway(){stop();}
bool LocalGateway::start(std::string address,std::uint16_t port){if(listener_>=0)return false;int fd=::socket(AF_INET,SOCK_STREAM,0),yes=1;if(fd<0)return false;::setsockopt(fd,SOL_SOCKET,SO_REUSEADDR,&yes,sizeof(yes));sockaddr_in a{};a.sin_family=AF_INET;a.sin_port=htons(port);if(::inet_pton(AF_INET,address.c_str(),&a.sin_addr)!=1||::bind(fd,reinterpret_cast<sockaddr*>(&a),sizeof(a))||::listen(fd,16)){::close(fd);status_.state=LocalGatewayState::Failed;return false;}socklen_t size=sizeof(a);if(::getsockname(fd,reinterpret_cast<sockaddr*>(&a),&size)!=0){::close(fd);status_.state=LocalGatewayState::Failed;return false;}listener_=fd;stopping_=false;status_={LocalGatewayState::Running,std::move(address),ntohs(a.sin_port)};thread_=new Thread([this]{run();});return true;}
void LocalGateway::stop()noexcept{stopping_=true;if(listener_>=0){::shutdown(listener_,SHUT_RDWR);::close(listener_);listener_=-1;}if(thread_){thread_->join();delete thread_;thread_=nullptr;}status_={};}LocalGatewayStatus LocalGateway::status()const{return status_;}
void LocalGateway::run()noexcept{while(!stopping_){int client=::accept(listener_,nullptr,nullptr);if(client<0)continue;Msg q;if(!read_request(client,q)){reply(client,400,"Bad Request");::close(client);continue;}auto h=hostname(q);if(h.empty()){reply(client,400,"Bad Request");::close(client);continue;}auto t=host_service_.local_gateway_target(h);if(t.result==LocalGatewayLookup::NotFound){reply(client,404,"Not Found");::close(client);continue;}if(t.result==LocalGatewayLookup::Unavailable){reply(client,503,"Service Unavailable");::close(client);continue;}int back=::socket(AF_INET,SOCK_STREAM,0);sockaddr_in a{};a.sin_family=AF_INET;a.sin_port=htons(t.port);a.sin_addr.s_addr=htonl(INADDR_LOOPBACK);if(back<0||::connect(back,reinterpret_cast<sockaddr*>(&a),sizeof(a))){if(back>=0)::close(back);reply(client,502,"Bad Gateway");::close(client);continue;}if(!send_all(back,wire(q))){::close(back);reply(client,502,"Bad Gateway");::close(client);continue;}::shutdown(back,SHUT_WR);Msg response;if(!read_response(back,response))reply(client,502,"Bad Gateway");else static_cast<void>(send_all(client,wire(response)));::close(back);::close(client);}}}
